=== ueberfuhr-trainings/java-xml-apis/src/test/resources/gameLibrary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/gameLibrary"
        elementFormDefault="qualified" xmlns:g="http://www.example.org/gameLibrary">

    <complexType name="Game">
        <sequence>
            <element name="title" type="string"/>
            <element name="genre" type="string"/>
            <element name="rating">
                <simpleType>
                    <restriction base="positiveInteger">
                        <maxInclusive value="10"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="timePlayed" type="duration"/>
            <element name="price" type="float"/>
        </sequence>
    </complexType>

    <element name="library">
        <complexType>
            <sequence>
                <element name="game" type="g:Game" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="game" type="g:Game"/>
</schema>

=== ueberfuhr-trainings/java-xml-apis/src/test/resources/gameLibrary.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns="http://www.example.org/gameLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/gameLibrary gameLibrary.xsd ">
	<game>
		<title>Elderscrolles IV: Skyrim</title>
		<genre>RPG</genre>
		<rating>9</rating>
		<timePlayed>P8DT18H56M23S</timePlayed>
		<price>14.99</price>
	</game>
	<game>
		<title>CS:GO</title>
		<genre>Shooter</genre>
		<rating>8</rating>
		<timePlayed>P40DT9H42M52S</timePlayed>
		<price>9.99</price>
	</game>
</library>
